import { Match } from "./types";

/**
 * Mock data — real stadiums, real teams, realistic coordinates.
 * Tier 1 = marquee (top derbies, elite clubs)
 * Tier 2 = standard top-flight
 * Tier 3 = lower-profile leagues
 */
export const MOCK_MATCHES: Match[] = [
  // ── EUROPE ──
  {
    id: "1",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeScore: 2,
    awayScore: 1,
    minute: 67,
    status: "LIVE",
    league: "Premier League",
    country: "England",
    stadium: "Emirates Stadium",
    latitude: 51.5549,
    longitude: -0.1084,
    tier: 1,
    leagueId: 39,
    categories: [],
    events: [
      { minute: 12, type: "goal", player: "Saka", team: "home" },
      { minute: 34, type: "goal", player: "Palmer", team: "away" },
      { minute: 58, type: "goal", player: "Havertz", team: "home" },
      { minute: 45, type: "yellow_card", player: "Caicedo", team: "away" },
    ],
  },
  {
    id: "11",
    homeTeam: "Liverpool",
    awayTeam: "Manchester City",
    homeScore: 1,
    awayScore: 1,
    minute: 38,
    status: "LIVE",
    league: "Premier League",
    country: "England",
    stadium: "Anfield",
    latitude: 53.4308,
    longitude: -2.9609,
    tier: 1,
    leagueId: 39,
    categories: [],
    events: [
      { minute: 15, type: "goal", player: "Salah", team: "home" },
      { minute: 30, type: "goal", player: "Haaland", team: "away" },
    ],
  },
  {
    id: "2",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    homeScore: 1,
    awayScore: 1,
    minute: 45,
    status: "HT",
    league: "La Liga",
    country: "Spain",
    stadium: "Santiago Bernabéu",
    latitude: 40.4531,
    longitude: -3.6883,
    tier: 1,
    leagueId: 140,
    categories: [],
    events: [
      { minute: 23, type: "goal", player: "Vinícius Jr.", team: "home" },
      { minute: 41, type: "goal", player: "Lewandowski", team: "away" },
    ],
  },
  {
    id: "12",
    homeTeam: "Atletico Madrid",
    awayTeam: "Sevilla",
    homeScore: 0,
    awayScore: 0,
    minute: null,
    status: "NS",
    league: "La Liga",
    country: "Spain",
    stadium: "Metropolitano",
    latitude: 40.4362,
    longitude: -3.5995,
    tier: 2,
    leagueId: 140,
    categories: [],
    events: [],
  },
  {
    id: "3",
    homeTeam: "Bayern Munich",
    awayTeam: "Borussia Dortmund",
    homeScore: 3,
    awayScore: 0,
    minute: 90,
    status: "FT",
    league: "Bundesliga",
    country: "Germany",
    stadium: "Allianz Arena",
    latitude: 48.2188,
    longitude: 11.6247,
    tier: 1,
    leagueId: 78,
    categories: [],
    events: [
      { minute: 15, type: "goal", player: "Kane", team: "home" },
      { minute: 52, type: "goal", player: "Musiala", team: "home" },
      { minute: 78, type: "goal", player: "Sané", team: "home" },
    ],
  },
  {
    id: "4",
    homeTeam: "AC Milan",
    awayTeam: "Inter Milan",
    homeScore: 0,
    awayScore: 0,
    minute: null,
    status: "NS",
    league: "Serie A",
    country: "Italy",
    stadium: "San Siro",
    latitude: 45.478,
    longitude: 9.124,
    tier: 1,
    leagueId: 135,
    categories: [],
    events: [],
  },
  {
    id: "13",
    homeTeam: "Juventus",
    awayTeam: "Napoli",
    homeScore: 2,
    awayScore: 1,
    minute: 82,
    status: "LIVE",
    league: "Serie A",
    country: "Italy",
    stadium: "Allianz Stadium",
    latitude: 45.1096,
    longitude: 7.6413,
    tier: 1,
    leagueId: 135,
    categories: [],
    events: [
      { minute: 20, type: "goal", player: "Vlahović", team: "home" },
      { minute: 55, type: "goal", player: "Osimhen", team: "away" },
      { minute: 71, type: "goal", player: "Yildiz", team: "home" },
    ],
  },
  {
    id: "5",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    homeScore: 2,
    awayScore: 0,
    minute: 33,
    status: "LIVE",
    league: "Ligue 1",
    country: "France",
    stadium: "Parc des Princes",
    latitude: 48.8414,
    longitude: 2.253,
    tier: 1,
    leagueId: 61,
    categories: [],
    events: [
      { minute: 11, type: "goal", player: "Dembélé", team: "home" },
      { minute: 29, type: "goal", player: "Barcola", team: "home" },
    ],
  },
  {
    id: "14",
    homeTeam: "Benfica",
    awayTeam: "Porto",
    homeScore: 1,
    awayScore: 0,
    minute: 60,
    status: "LIVE",
    league: "Liga Portugal",
    country: "Portugal",
    stadium: "Estádio da Luz",
    latitude: 38.7527,
    longitude: -9.1847,
    tier: 2,
    leagueId: 94,
    categories: [],
    events: [
      { minute: 44, type: "goal", player: "Pavlidis", team: "home" },
    ],
  },
  {
    id: "15",
    homeTeam: "Ajax",
    awayTeam: "PSV",
    homeScore: 2,
    awayScore: 2,
    minute: 90,
    status: "FT",
    league: "Eredivisie",
    country: "Netherlands",
    stadium: "Johan Cruyff Arena",
    latitude: 52.3142,
    longitude: 4.9419,
    tier: 2,
    leagueId: 88,
    categories: [],
    events: [
      { minute: 10, type: "goal", player: "Brobbey", team: "home" },
      { minute: 35, type: "goal", player: "De Jong", team: "away" },
      { minute: 62, type: "goal", player: "Taylor", team: "home" },
      { minute: 88, type: "goal", player: "Tillman", team: "away" },
    ],
  },

  // ── SOUTH AMERICA ──
  {
    id: "6",
    homeTeam: "Flamengo",
    awayTeam: "Palmeiras",
    homeScore: 1,
    awayScore: 2,
    minute: 72,
    status: "LIVE",
    league: "Brasileirão",
    country: "Brazil",
    stadium: "Maracanã",
    latitude: -22.9121,
    longitude: -43.2302,
    tier: 2,
    leagueId: 71,
    categories: [],
    events: [
      { minute: 18, type: "goal", player: "Endrick", team: "away" },
      { minute: 44, type: "goal", player: "Gerson", team: "home" },
      { minute: 65, type: "goal", player: "Estêvão", team: "away" },
    ],
  },
  {
    id: "8",
    homeTeam: "River Plate",
    awayTeam: "Boca Juniors",
    homeScore: 0,
    awayScore: 0,
    minute: null,
    status: "NS",
    league: "Liga Profesional",
    country: "Argentina",
    stadium: "Estadio Monumental",
    latitude: -34.5453,
    longitude: -58.4498,
    tier: 1,
    leagueId: 128,
    categories: [],
    events: [],
  },
  {
    id: "16",
    homeTeam: "Corinthians",
    awayTeam: "São Paulo",
    homeScore: 0,
    awayScore: 1,
    minute: 15,
    status: "LIVE",
    league: "Brasileirão",
    country: "Brazil",
    stadium: "Neo Química Arena",
    latitude: -23.5453,
    longitude: -46.4744,
    tier: 2,
    leagueId: 71,
    categories: [],
    events: [
      { minute: 8, type: "goal", player: "Luciano", team: "away" },
    ],
  },

  // ── ASIA ──
  {
    id: "7",
    homeTeam: "Al Hilal",
    awayTeam: "Al Nassr",
    homeScore: 1,
    awayScore: 1,
    minute: 55,
    status: "LIVE",
    league: "Saudi Pro League",
    country: "Saudi Arabia",
    stadium: "Kingdom Arena",
    latitude: 24.7136,
    longitude: 46.6753,
    tier: 2,
    leagueId: 307,
    categories: [],
    events: [
      { minute: 22, type: "goal", player: "Mitrović", team: "home" },
      { minute: 38, type: "goal", player: "Ronaldo", team: "away" },
    ],
  },
  {
    id: "10",
    homeTeam: "Yokohama F. Marinos",
    awayTeam: "Vissel Kobe",
    homeScore: 1,
    awayScore: 0,
    minute: 20,
    status: "LIVE",
    league: "J1 League",
    country: "Japan",
    stadium: "Nissan Stadium",
    latitude: 35.51,
    longitude: 139.6064,
    tier: 3,
    leagueId: 169,
    categories: [],
    events: [
      { minute: 14, type: "goal", player: "Anderson Lopes", team: "home" },
    ],
  },
  {
    id: "17",
    homeTeam: "Ulsan HD",
    awayTeam: "Jeonbuk Motors",
    homeScore: 3,
    awayScore: 1,
    minute: 90,
    status: "FT",
    league: "K League 1",
    country: "South Korea",
    stadium: "Munsu Football Stadium",
    latitude: 35.5338,
    longitude: 129.2731,
    tier: 3,
    leagueId: 292,
    categories: [],
    events: [
      { minute: 12, type: "goal", player: "Joo Min-kyu", team: "home" },
      { minute: 40, type: "goal", player: "Kim Jin-su", team: "away" },
      { minute: 60, type: "goal", player: "Oh Se-hun", team: "home" },
      { minute: 85, type: "goal", player: "Joo Min-kyu", team: "home" },
    ],
  },

  // ── AFRICA ──
  {
    id: "9",
    homeTeam: "Kaizer Chiefs",
    awayTeam: "Orlando Pirates",
    homeScore: 2,
    awayScore: 2,
    minute: 88,
    status: "LIVE",
    league: "PSL",
    country: "South Africa",
    stadium: "FNB Stadium",
    latitude: -26.2325,
    longitude: 27.9828,
    tier: 3,
    leagueId: 200,
    categories: [],
    events: [
      { minute: 10, type: "goal", player: "Mofokeng", team: "away" },
      { minute: 35, type: "goal", player: "Shabalala", team: "home" },
      { minute: 61, type: "goal", player: "Shabalala", team: "home" },
      { minute: 80, type: "goal", player: "Saleng", team: "away" },
    ],
  },
  {
    id: "18",
    homeTeam: "Al Ahly",
    awayTeam: "Zamalek",
    homeScore: 1,
    awayScore: 0,
    minute: 45,
    status: "HT",
    league: "Egyptian Premier League",
    country: "Egypt",
    stadium: "Cairo International Stadium",
    latitude: 30.0694,
    longitude: 31.3131,
    tier: 2,
    leagueId: 233,
    categories: [],
    events: [
      { minute: 32, type: "goal", player: "Taher", team: "home" },
    ],
  },

  // ── NORTH AMERICA ──
  {
    id: "19",
    homeTeam: "LAFC",
    awayTeam: "LA Galaxy",
    homeScore: 0,
    awayScore: 0,
    minute: null,
    status: "NS",
    league: "MLS",
    country: "United States",
    stadium: "BMO Stadium",
    latitude: 34.0128,
    longitude: -118.2841,
    tier: 3,
    leagueId: 253,
    categories: [],
    events: [],
  },
  {
    id: "20",
    homeTeam: "Club América",
    awayTeam: "Guadalajara",
    homeScore: 2,
    awayScore: 1,
    minute: 90,
    status: "FT",
    league: "Liga MX",
    country: "Mexico",
    stadium: "Estadio Azteca",
    latitude: 19.3029,
    longitude: -99.1505,
    tier: 3,
    leagueId: 262,
    categories: [],
    events: [
      { minute: 25, type: "goal", player: "Henry Martín", team: "home" },
      { minute: 50, type: "goal", player: "Chicharito", team: "away" },
      { minute: 78, type: "goal", player: "Valdés", team: "home" },
    ],
  },
];
